include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore # freezed    
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
    - scripts/**
    - test/test_packages/**

linter:
  rules:
    - unawaited_futures