name: dart_apitool
description: A tool for Dart APIs

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies: 
  analyzer: ^4.3.1
  args: ^2.3.1
  equatable: ^2.0.3
  path: ^1.8.2
  stack: ^0.2.1

dev_dependencies: 
  flutter_lints: ^2.0.1
