name: dart_apitool
description: A tool for Dart APIs

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies: 
  analyzer: ^4.3.1
  args: ^2.3.1

dev_dependencies:

