name: dart_apitool
description: A tool for Dart APIs. It allows to create a model of the public API of a given package as well as comparing two different models and provide the needed version jump.
homepage: https://devmil.de
repository: https://github.com/devmil/dart_apitool
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies: 
  analyzer: ^4.3.1
  args: ^2.3.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  path: ^1.8.2
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.0
  stack: ^0.2.1

dev_dependencies: 
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.4
 